name: PR with gif

on:
  push:
    branches:
      - master
    # paths:
    #   - k8gb.py
  pull_request:
    branches:
      - master
    paths:
      - k8gb.py

jobs:
  gif-pr:
    runs-on: ubuntu-latest
    # container: manimcommunity/manim:v0.12.0
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes
        # uses: manim-kindergarten/manim_action_renderer@master
        # uses: docker://manimcommunity/manim:v0.12.0
        uses: ./
        id: renderer
        with:
          cmd: k8gb.py --progress_bar none -qh --format=gif
        # with:
        #   community_ver: true
        #   manim_repo: https://github.com/ManimCommunity/manim
        #   source_file: k8gb.py
        #   scene_names: |
        #     FailOver
        #   args: "-qh --format=gif"

      # - name: Copy the gif file
      #   run: |
      #     tree ${{ steps.renderer.outputs.video_path }}
      #     mv $(find ./media/videos/ -name "*.gif") ./k8gb.gif
      #     rm -rf ${{ steps.renderer.outputs.video_path }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update gif animation"
          body: |
            :package: :framed_picture: :gift:
            New gif has been rendered.

            This automated PR was created by [this action][1].

            [1]: https://github.com/k8gb-io/k8gb-manim/actions/runs/${{ github.run_id }}
          branch: gif_update
          delete-branch: true
          base: master
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check PR
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"