name: PR with gif

on:
  push:
    branches:
      - master
    paths:
      - k8gb.py
  pull_request:
    branches:
      - master
    paths:
      - k8gb.py

jobs:
  gif-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes
        uses: ./
        id: renderer
        with:
          # cmd: k8gb.py Dummy --progress_bar none -ql --format=gif --fps 1
          cmd: k8gb.py FailOver --progress_bar none -ql --format=gif --fps 10
      - name: Create commit
        id: commit
        run: |
          git config user.name 'jkremser'
          git config user.email 'jiri.kremser@gmail.com'
          git add -A
          git commit -s -m "Update low-quality gif file"
          sha=$(git rev-parse HEAD)
          echo "::set-output name=sha::${sha}"
          echo ${sha}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update gif animation"
          body: |
            :package: :framed_picture: :gift:
            New gif(t) has been rendered.

            ![preview](https://github.com/k8gb-io/k8gb-manim/raw/${{ steps.commit.outputs.sha }}/example/k8gb-low-q.gif)

            This automated PR was created by [this action][1].

            [1]: https://github.com/k8gb-io/k8gb-manim/actions/runs/${{ github.run_id }}
          branch: gif_update
          delete-branch: true
          base: master
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check PR
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
